### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by benjamin-kirkbride** [ssaenger/LED_Matrix#1]
Hi, what is this project licensed under?

Thanks!

**Comment by ssaenger** [comment]
It's whatever the license is of the libraries I am using. As far as I can tell, MIT. You are free to use/distribute/modify any code in this project. Sorry for the late reply.

**Comment by benjamin-kirkbride** [comment]
@ssaenger could you add a license file to the repo for convenience :)

**Comment by ssaenger** [comment]
Done. Knock yourself out.
